# Generated by Django 5.2.3 on 2025-06-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_director', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=50)),
                ('practice_supervisor', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=150)),
            ],
        ),
    ]
